
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    # volumes:
    #   - .:/app
    environment:
      FLASK_ENV: development

    command: bash -c "flask --app main run  --host=0.0.0.0"
  svelte-app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    # volumes:
    #   - ./frontend:/app

    command: bash -c "cd /app && npm run dev  -- --host=0.0.0.0"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
